### ISSUE TITLE
Wrong value for road temp

### ISSUE THREAD

**Issue by dogmatic69** [gjohansson-ST/pytrafikverket#33]
I've had an alert on the roat temp for a few years now and recently I've started getting rogue alerts where the temperature is reported as 0'C but it's 30'C outside. 

Looking into the code it seems there was some [changes lately](https://github.com/endor-force/pytrafikverket/commit/2408639bbd1b33d5cd5121afe9676c94e8111e45) which is probably related as this is around the time it started.

The trace from the automation:
```
  to_state:
    entity_id: sensor.xxx_road_temperature
    state: '0'
    attributes:
      state_class: measurement
      unit_of_measurement: °C
      attribution: Data provided by Trafikverket
      device_class: temperature
      friendly_name: xxx Road temperature
    last_changed: '2023-06-19T09:07:46.249516+00:00'
    last_updated: '2023-06-19T09:07:46.249516+00:00'
    context:
      id: 01H39EJ0Y9KGNCRBZHG29M1QMA
      parent_id: null
      user_id: null
  for: null
  description: numeric state of sensor.xxx_road_temperature
```
![image](https://github.com/endor-force/pytrafikverket/assets/94674/424321b8-44e1-4b7e-9568-a0b5f8417b2c)
